### ISSUE TITLE
Pact (+ Exploiter) Great Power, Greater Expense not Stacking with Favored Metamagic: Persistent 

### ISSUE THREAD

**Issue by alexgadam** [kreaddy/MysticalMayhem#18]
Cheers for this great mod. One bug report.

Great Power, Greater Expense lets you treat any spells granted by your patron/oracle curse as being -1 resultant level on applying metamagic to them. 

Tabletop Tweaks enables Favored Metamagic: Persistent. 

An Ancestors Patron pact wizard with Favored Metamagic: Persistent should therefore be able to prepare persistent weird in Level 9 slots. Unfortunately this doesn't work :(

**Comment by kreaddy** [comment]
All right, after investigation this is neither a bug in this mod nor a compatibility issue with TTT. It's just that the game ignores all cost lowering abilities (even those in the base game), using the default cost to calculate if a spell with metamagic has a level higher than 10. If a metamagic feat raise the level of a spell to at least 11 _without any cost reduction_, then the feat can't be applied at all.

Owlcat may have done this to prevent the use of metamagic with level 10 spells or maybe because of some weirdness with respecs. I'm not sure for now.

**Comment by kreaddy** [comment]
I can say for sure now I'm not going to change this behavior. It's a outside the scope of this mod and I feel like it's too unsafe at the moment.
