### ISSUE TITLE
Spontaneous cast for shadow patron pact wizard spells

### ISSUE THREAD

**Issue by waleramir** [kreaddy/MysticalMayhem#2]
![image](https://user-images.githubusercontent.com/42164244/195996669-711cc6b6-f553-4572-98a0-ba7d7d9ca329.png)
Spontaneous cast for shadow patron pact wizard spells which require additional menu doesn't work, for example Phantasmall killer -> Shadow conjuration -> Nothing happens (should have pop-up menu for lower level conj spells).

**Comment by kreaddy** [comment]
Ah yeah it seems you can't have nested variants in the game. I'll have to put all possible shadow conjuration choices in there I guess.

**Comment by waleramir** [comment]
Yea, but there is a problem. You can have shadow conjuration, shadow evocation, greater shadow evocation and greater shadow conjuration simultaneously at spontaneous window menu. So amount of spell will go over the roof because you copy all evoc and conj spells up to 4 level spells and then copy of all evoc and cong up to 7 level for greater version. There may be doubling of 1-3 lvl spells because of that conversion as you need to calc DC for the spell differently.

**Comment by kreaddy** [comment]
All right it's fixed now. Spells are correctly recognized as coming from the relevant shadows spell and duplicates are removed. Level 9 menu is still pretty big but there's nothing I can do about that without reworking the UI entirely (and I'm not doing something like this just because one patron is annoying).
![fixed](https://user-images.githubusercontent.com/95177331/196032576-67a37221-d304-41ee-9eb6-bdf5b1964c9d.jpg)
